Can't test grpc examples with Java 21+ currently
Because of https://github.com/lightbend/ssl-config/issues/367
Exception:
java.lang.IllegalArgumentException: GrpcClientSettings requires a server endpoint with ssl, but none provided